apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: mohin786/myimage:v2
          ports:
            - containerPort: 8080
          resources:
            requests: 
              cpu: 400m
              memory: 10Mi    
      nodeSelector:
        cloud.google.com/gke-nodepool: scaling-node-pool     
